### ISSUE TITLE
Calibration graph can be cheated by the algorithm which always predicts the average.

### ISSUE THREAD

**Issue by L-M-Sherlock** [open-spaced-repetition/spaced-repetition-algorithm-metric#1]
@Expertium, I create a notebook to compare metrics. I guess you would be interested:

https://github.com/open-spaced-repetition/spaced-repetition-algorithm-metric/blob/main/metrics_research.ipynb

**Comment by Expertium** [comment]
Yeah, I know. The idea with bins only works if the algorithm outputs more than 1 value. If it only outputs one value, then there will only be one bin.
Also, why did you choose 60 and 96?
`for R in range(60, 96):`

**Comment by Expertium** [comment]
![image](https://github.com/open-spaced-repetition/spaced-repetition-algorithm-metric/assets/83031600/c6879330-dcd4-47e1-9eb1-547b4f881c0b)
This is what the results look like with `for R in range(1, 99):`

**Comment by L-M-Sherlock** [comment]
> Also, why did you choose 60 and 96?

Because most users' retention is in the range of 60 and 96 if they used spaced repetition software.

**Comment by Expertium** [comment]
```
import random
from scipy import stats

a = 4.5
b = 1.5
sample_size = 100_000

number = stats.beta.rvs(a, b, size=sample_size)

p = [x for x in number]
y = [1 if random.random() < x else 0 for x in p]
```

This is a more nice and elegant way of doing it.
![image](https://github.com/open-spaced-repetition/spaced-repetition-algorithm-metric/assets/83031600/6e2a14ea-d126-48a9-9846-421c4ac60a8d)

**Comment by L-M-Sherlock** [comment]
Nice! I update the notebook with your code.

**Comment by Expertium** [comment]
As for cheating by always outputing the average, the universal metric cannot be cheated that way, but it also requires a second algorithm. If we are evaluating just one algorithm, then yes, metrics based on binning can be cheated.
